language: php

env:
  global:
    - XDEBUG_MODE=coverage

php:
  - 7.4
  - 8.0

before_script:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/test-reporter
